version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    filename: logs/simulation.log
    formatter: simple
    level: INFO
root:
  level: INFO
  handlers: [ file ]
